Repository gudtldn/GTL_W12_T1, pull requests merged in 2025-05, with the labels that each got.

#2 feat: EditCondition 추가로 프로퍼티 노출 조건 제어 기능 구현
  EngineSIU/EngineSIU/Engine/Source/Runtime/CoreUObject/UObject/PropertyDisplay.cpp
  EngineSIU/EngineSIU/Engine/Source/Runtime/CoreUObject/UObject/PropertyMetadata.h
Labels: size/S

#5 Add PhysX physics engine initialization and simulation
  EngineSIU/EngineSIU/Engine/Source/Runtime/Engine/Classes/Engine/EditorEngine.cpp
  EngineSIU/EngineSIU/Engine/Source/Runtime/Engine/Classes/PhysicsEngine/PhysX/PhysX.cpp
  EngineSIU/EngineSIU/Engine/Source/Runtime/Engine/Classes/PhysicsEngine/PhysX/PhysX.h
  EngineSIU/EngineSIU/Engine/Source/Runtime/Launch/EngineLoop.cpp
  EngineSIU/EngineSIU/EngineSIU.vcxproj
Labels: size/L

#6 Feature/depth of field
  EngineSIU/EngineSIU/Engine/Source/Editor/PropertyEditor/ControlEditorPanel.cpp
  EngineSIU/EngineSIU/Engine/Source/Runtime/Launch/Define.h
  EngineSIU/EngineSIU/Engine/Source/Runtime/Renderer/CompositingPass.cpp
  EngineSIU/EngineSIU/Engine/Source/Runtime/Renderer/PostProcess/DepthOfFieldRenderPass.cpp
  EngineSIU/EngineSIU/Shaders/DownSampleShader.hlsl
Labels: size/M

#7 Add physics simulation enhancements and refactor code
  EngineSIU/EngineSIU/Engine/Source/Runtime/Core/Math/Transform.h
  EngineSIU/EngineSIU/Engine/Source/Runtime/CoreUObject/UObject/Property.h
  EngineSIU/EngineSIU/Engine/Source/Runtime/CoreUObject/UObject/PropertyDisplay.cpp
  EngineSIU/EngineSIU/Engine/Source/Runtime/Engine/Classes/Components/PrimitiveComponent.cpp
  EngineSIU/EngineSIU/Engine/Source/Runtime/Engine/Classes/Components/PrimitiveComponent.h
  EngineSIU/EngineSIU/Engine/Source/Runtime/Engine/Classes/Components/SceneComponent.cpp
  EngineSIU/EngineSIU/Engine/Source/Runtime/Engine/Classes/Components/SceneComponent.h
  EngineSIU/EngineSIU/Engine/Source/Runtime/Engine/Classes/Components/SkeletalMeshComponent.cpp
  EngineSIU/EngineSIU/Engine/Source/Runtime/Engine/Classes/Components/SkeletalMeshComponent.h
  EngineSIU/EngineSIU/Engine/Source/Runtime/Engine/Classes/Components/StaticMeshComponent.h
  EngineSIU/EngineSIU/Engine/Source/Runtime/Engine/Classes/Engine/StaticMesh.cpp
  EngineSIU/EngineSIU/Engine/Source/Runtime/Engine/Classes/Engine/StaticMesh.h
  EngineSIU/EngineSIU/Engine/Source/Runtime/Engine/Classes/Particles/Location/ParticleModuleLocation.cpp
  EngineSIU/EngineSIU/Engine/Source/Runtime/Engine/Classes/Particles/Velocity/ParticleModuleVelocity.cpp
  EngineSIU/EngineSIU/Engine/Source/Runtime/Engine/Classes/Particles/Velocity/ParticleModuleVelocityOverLife.cpp
  EngineSIU/EngineSIU/Engine/Source/Runtime/Engine/Classes/PhysicsEngine/AggregateGeom.h
  EngineSIU/EngineSIU/Engine/Source/Runtime/Engine/Classes/PhysicsEngine/BodyInstance.cpp
  EngineSIU/EngineSIU/Engine/Source/Runtime/Engine/Classes/PhysicsEngine/BodyInstance.h
  EngineSIU/EngineSIU/Engine/Source/Runtime/Engine/Classes/PhysicsEngine/BodySetup.h
  EngineSIU/EngineSIU/Engine/Source/Runtime/Engine/Classes/PhysicsEngine/BoxElem.h
  EngineSIU/EngineSIU/Engine/Source/Runtime/Engine/Classes/PhysicsEngine/ConstraintInstance.h
  EngineSIU/EngineSIU/Engine/Source/Runtime/Engine/Classes/PhysicsEngine/ConvexElem.h
  EngineSIU/EngineSIU/Engine/Source/Runtime/Engine/Classes/PhysicsEngine/PhysX/PhysX.cpp
  EngineSIU/EngineSIU/Engine/Source/Runtime/Engine/Classes/PhysicsEngine/PhysX/PhysX.h
  EngineSIU/EngineSIU/Engine/Source/Runtime/Engine/Classes/PhysicsEngine/PhysicsAsset.h
  EngineSIU/EngineSIU/Engine/Source/Runtime/Engine/Classes/PhysicsEngine/SphereElem.h
  EngineSIU/EngineSIU/Engine/Source/Runtime/Engine/Classes/PhysicsEngine/SphylElem.h
  EngineSIU/EngineSIU/Engine/Source/Runtime/Launch/EngineLoop.cpp
  EngineSIU/EngineSIU/EngineSIU.vcxproj
Labels: size/XXL

#8 충돌 필터링 및 이벤트 처리 개선 사항 추가
  EngineSIU/EngineSIU/Engine/Source/Runtime/CoreUObject/UObject/Property.h
  EngineSIU/EngineSIU/Engine/Source/Runtime/CoreUObject/UObject/PropertyTypes.h
  EngineSIU/EngineSIU/Engine/Source/Runtime/Engine/Classes/Components/PrimitiveComponent.h
  EngineSIU/EngineSIU/Engine/Source/Runtime/Engine/Classes/Engine/EngineTypes.h
  EngineSIU/EngineSIU/Engine/Source/Runtime/Engine/Classes/PhysicsEngine/BodyInstance.cpp
  EngineSIU/EngineSIU/Engine/Source/Runtime/Engine/Classes/PhysicsEngine/BodySetup.cpp
  EngineSIU/EngineSIU/Engine/Source/Runtime/Engine/Classes/PhysicsEngine/BodySetup.h
  EngineSIU/EngineSIU/Engine/Source/Runtime/Engine/Classes/PhysicsEngine/PhysX/FSimulationEventCallback.cpp
  EngineSIU/EngineSIU/Engine/Source/Runtime/Engine/Classes/PhysicsEngine/PhysX/FSimulationEventCallback.h
  EngineSIU/EngineSIU/Engine/Source/Runtime/Engine/Classes/PhysicsEngine/PhysX/PhysX.cpp
  EngineSIU/EngineSIU/Engine/Source/Runtime/Engine/Classes/PhysicsEngine/PhysX/PhysX.h
  EngineSIU/EngineSIU/EngineSIU.vcxproj
Labels: size/XL
